### ISSUE TITLE
upload brand logos

### ISSUE THREAD

**Issue by effyyzhang** [jtanadi/sv-starter-pack#57]
<img width="240" alt="logo_all_bird" src="https://user-images.githubusercontent.com/4413445/67622310-5a89d800-f7e7-11e9-9ef3-7ae6c583c269.png">
<img width="240" alt="logo_apple" src="https://user-images.githubusercontent.com/4413445/67622311-5a89d800-f7e7-11e9-80c3-ad65748b45b6.png">
<img width="240" alt="logo_boosted" src="https://user-images.githubusercontent.com/4413445/67622312-5a89d800-f7e7-11e9-938d-0f80444e3e6a.png">
<img width="240" alt="logo_doordash" src="https://user-images.githubusercontent.com/4413445/67622313-5a89d800-f7e7-11e9-81df-62f6e77b3add.png">
<img width="240" alt="logo_everlane" src="https://user-images.githubusercontent.com/4413445/67622314-5a89d800-f7e7-11e9-9162-4b9190978f70.png">
<img width="240" alt="logo_google" src="https://user-images.githubusercontent.com/4413445/67622315-5a89d800-f7e7-11e9-8794-5f6249be74a1.png">
<img width="240" alt="logo_moleskine" src="https://user-images.githubusercontent.com/4413445/67622316-5a89d800-f7e7-11e9-81e3-0e8fc3d9670e.png">
<img width="240" alt="logo_rains" src="https://user-images.githubusercontent.com/4413445/67622317-5a89d800-f7e7-11e9-89f5-75faea33bc65.png">
<img width="240" alt="logo_soylent" src="https://user-images.githubusercontent.com/4413445/67622318-5a89d800-f7e7-11e9-8ee7-b2ed180ef614.png">
<img width="240" alt="logo_stiga" src="https://user-images.githubusercontent.com/4413445/67622319-5b226e80-f7e7-11e9-9e83-11ba34cca5de.png">
<img width="240" alt="logo_tesla" src="https://user-images.githubusercontent.com/4413445/67622320-5b226e80-f7e7-11e9-9746-b378084d2689.png">
<img width="240" alt="logo_uber" src="https://user-images.githubusercontent.com/4413445/67622321-5b226e80-f7e7-11e9-9b19-d711b17ee192.png">
<img width="240" alt="logo_vivora" src="https://user-images.githubusercontent.com/4413445/67622322-5b226e80-f7e7-11e9-885b-68f09c091211.png">

**Comment by jtanadi** [comment]
Closed because logos have been uploaded.
